### ISSUE TITLE
Use OpenVINO from conda-forge instead of archives

### ISSUE THREAD

**Issue by ilya-lavrenov** [yangsu2022/OV_SD_CPP#1]
Instead of:
https://github.com/yangsu2022/OV_SD_CPP/blob/fe65b6c069e8b1ea25870f0e1b2fa288b3ddd755/scripts/build_dependencies.sh#L112-L153
You can just use:
```
conda install -c "conda-forge/label/openvino_dev" openvino
```
For pre-releases

Or even simplier:
```
conda install -c conda-forge openvino
```
If validated release is enough.

See https://anaconda.org/conda-forge/openvino/

It's good to advertise conda-forge channel since current script already implies conda is installed

**Comment by yangsu2022** [comment]
Hi ilya, Thanks for the kind reminding. 

- Will user need to set up the env variable? I didn't find setupvars.sh  
- Seems conda-forge not provide OV samples like archives? 
- Could you share me some links for the C++ OV usage guide with conda-forge? 

Thanks

**Comment by ilya-lavrenov** [comment]
Hi @yangsu2022 

> Will user need to set up the env variable? I didn't find setupvars.sh

No, OpenVINO installed into conda environment is activated together with this environment: 
```bash
conda install -c conda-forge openvino
# you can immediately use OpenVINO, e.g. call `ovc` tool
# or build C++ projects via cmake
```

> Seems conda-forge not provide OV samples like archives?

Yes, but why do you need samples in this repo?

> Could you share me some links for the C++ OV usage guide with conda-forge?

Usage is the same as you've installed OpenVINO via archive - install using the command above and use, but no needs to call setupvars.sh, because it's activated automatically. 

OpenVINO installation and usage guide for conda-forge channel https://docs.openvino.ai/2023.1/openvino_docs_install_guides_installing_openvino_conda.html#compiling-with-openvino-runtime-from-conda-forge-on-linux

**Comment by yangsu2022** [comment]
Thanks for your quick reply! conda-forge really simplify the installation process! 
I update the script in this [commit](https://github.com/yangsu2022/OV_SD_CPP/commit/5e786792a6ffc3b5dd44f060fd38b2d2cfccb9c4)
